server:
  port: 8085

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j.bulkhead:
  instances:
    bulkheadService1:
      maxWaitDuration: 1000ms
      maxConcurrentCall: 2

resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadService1:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1